# Dependabot will run on day 9 of each month at 02:02 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "2 2 9 * *"
    open-pull-requests-limit: 20
    assignees:
      - "oelison"
    versioning-strategy: "increase"
